name: localcooks_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get: ^4.6.6
  intl: ^0.20.2
  dio_cache_interceptor: ^3.5.1
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  artools: ^0.0.3+5
  image_picker: ^1.1.2
  shared_preferences: ^2.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: any
  #flex_color_sche`me: ^8.1.1
  flutter_advanced_drawer: ^1.4.0
  google_nav_bar: ^5.0.7
  flutter_google_places_hoc081098: ^2.0.0
  google_api_headers: ^4.3.3
  google_maps_webservice2: ^1.0.5
  google_maps_flutter: ^2.10.0
  geocoding: ^2.0.5
  material_design_icons_flutter: ^7.0.7296
  location: ^7.0.1
  permission_handler:
  geolocator:
  slide_action: ^0.0.2
  pin_code_fields: ^8.0.1
  custom_rating_bar: ^3.0.0
  flutter_html: ^3.0.0
  flutter_stripe: ^11.4.0
  easy_stepper: ^0.8.5+1

dependency_overrides:
  meta: 1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
